"""
Project Euler #2
Lewis J Ellis

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

"""
This approach is tailored to the use.
A more general approach would write a memozing fibonacci function and iterate over it.
For this use, I feel like that's overkill.
"""

s = 0
p1 = 1
p2 = 1
n = p1 + p2 
while n < 4000000:
  if n % 2 == 0:
    s += n
  p1 = p2
  p2 = n
  n = p1 + p2
print s
